data:
  device:
    train_dir: ./data/raw/device/train
    test_dir: ./data/raw/device/test
  power:
    train_dir: ./data/raw/power/train
    test_dir: ./data/raw/power/test
  RIS:
    train_dir: ./data/raw/RIS/train
    test_dir: ./data/raw/RIS/test
    
data_from_cvx:
  device:
    train_dir: ./data/from_cvx/device/train
    test_dir: ./data/from_cvx/device/test
  power:
    train_dir: ./data/from_cvx/power/train
    test_dir: ./data/from_cvx/power/test
  RIS:
    train_dir: ./data/from_cvx/ris/train
    test_dir: ./data/from_cvx/ris/test

training:
  batch_size: 500
  epochs: 10
  learning_rate: 0.02
  
params:
  num_device: [3, 5, 7, 9, 11, 13]
  num_RIS: [10, 20, 30, 40, 50, 60]
  power_bar: [4, 5, 6, 7, 8, 9, 10, 11, 12]
  