data:
  device:
    train_dir: ./data/raw/device/train
    test_dir: ./data/raw/device/test
  power:
    train_dir: ./data/raw/power/train
    test_dir: ./data/raw/power/test
  RIS:
    train_dir: ./data/raw/RIS/train
    test_dir: ./data/raw/RIS/test

training:
  batch_size: 500
  epochs: 10
  learning_rate: 0.02
  
params:
  num_device: [3, 5, 7, 9, 11, 13]
  num_RIS: [5, 10, 15, 20, 30, 40, 50]
  power_bar: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
  